sonar.projectKey=fliply
sonar.projectName=fliply
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
#sonar.token=squ_656d7853a772c152697eae36c5b3e89057efcfd4